apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
    tier: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
